
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class givefeedback extends javax.swing.JFrame {

    /**
     * Creates new form givefeedback
     */
    public givefeedback() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1_givefeedback = new javax.swing.JButton();
        jLabel1_givefeedback = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_givefeedback = new javax.swing.JTextArea();
        jRadioButton1_givefeedback = new javax.swing.JRadioButton();
        jRadioButton2_givefeedback = new javax.swing.JRadioButton();
        jRadioButton3_givefeedback = new javax.swing.JRadioButton();
        jRadioButton4_givefeedback = new javax.swing.JRadioButton();
        jRadioButton5_givefeedback = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1_givefeedback.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_givefeedback.setText("Submit");
        jButton1_givefeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_givefeedbackActionPerformed(evt);
            }
        });

        jLabel1_givefeedback.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1_givefeedback.setText("How satisfied are you with our application ?");

        jTextArea1_givefeedback.setColumns(20);
        jTextArea1_givefeedback.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_givefeedback);

        buttonGroup1.add(jRadioButton1_givefeedback);
        jRadioButton1_givefeedback.setText("1");
        jRadioButton1_givefeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_givefeedbackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2_givefeedback);
        jRadioButton2_givefeedback.setText("2");
        jRadioButton2_givefeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_givefeedbackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3_givefeedback);
        jRadioButton3_givefeedback.setText("3");
        jRadioButton3_givefeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_givefeedbackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4_givefeedback);
        jRadioButton4_givefeedback.setText("4");

        buttonGroup1.add(jRadioButton5_givefeedback);
        jRadioButton5_givefeedback.setText("5");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-32.png"))); // NOI18N
        jLabel13.setToolTipText("");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jRadioButton1_givefeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2_givefeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3_givefeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4_givefeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5_givefeedback))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1_givefeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1_givefeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1_givefeedback)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5_givefeedback)
                    .addComponent(jRadioButton4_givefeedback)
                    .addComponent(jRadioButton3_givefeedback)
                    .addComponent(jRadioButton2_givefeedback)
                    .addComponent(jRadioButton1_givefeedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1_givefeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1_givefeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_givefeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1_givefeedbackActionPerformed

    private void jRadioButton3_givefeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_givefeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3_givefeedbackActionPerformed

    private void jButton1_givefeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_givefeedbackActionPerformed
        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/softproj","root","");
            
        Statement st = con.createStatement();
        
        String s="";
        if(this.jRadioButton1_givefeedback.isSelected() == true)
        {
            
        s= "INSERT INTO `feedbacks` (`fb_id`, `user_id`, `decreption`, `feedback_stars`) VALUES (NULL, '"+Login.currentUser.getUserID()+"', '"+this.jTextArea1_givefeedback.getText()+"', '1');";
        }
        
        if(this.jRadioButton2_givefeedback.isSelected() == true)
        {
            
        s= "INSERT INTO `feedbacks` (`fb_id`, `user_id`, `decreption`, `feedback_stars`) VALUES (NULL, '"+Login.currentUser.getUserID()+"', '"+this.jTextArea1_givefeedback.getText()+"', '2');";
        }
        
        
        if(this.jRadioButton3_givefeedback.isSelected() == true)
        {
            
        s= "INSERT INTO `feedbacks` (`fb_id`, `user_id`, `decreption`, `feedback_stars`) VALUES (NULL, '"+Login.currentUser.getUserID()+"', '"+this.jTextArea1_givefeedback.getText()+"', '3');";
        }
        
        
        if(this.jRadioButton4_givefeedback.isSelected() == true)
        {
            
        s= "INSERT INTO `feedbacks` (`fb_id`, `user_id`, `decreption`, `feedback_stars`) VALUES (NULL, '"+Login.currentUser.getUserID()+"', '"+this.jTextArea1_givefeedback.getText()+"', '4');";
        }
        
        
        
        if(this.jRadioButton5_givefeedback.isSelected() == true)
        {
            
        s= "INSERT INTO `feedbacks` (`fb_id`, `user_id`, `decreption`, `feedback_stars`) VALUES (NULL, '"+Login.currentUser.getUserID()+"', '"+this.jTextArea1_givefeedback.getText()+"', '5');";
        }
            
        st.executeUpdate(s);
        con.close();
        JOptionPane.showMessageDialog(null, "Your feedback added Succefully");
        
        } catch (Exception ex) {
            Logger.getLogger(givefeedback.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
        
        
       
    }//GEN-LAST:event_jButton1_givefeedbackActionPerformed

    private void jRadioButton2_givefeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_givefeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2_givefeedbackActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       userInterface face=new userInterface();
        
        face.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(givefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(givefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(givefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(givefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new givefeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_givefeedback;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel1_givefeedback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_givefeedback;
    private javax.swing.JRadioButton jRadioButton2_givefeedback;
    private javax.swing.JRadioButton jRadioButton3_givefeedback;
    private javax.swing.JRadioButton jRadioButton4_givefeedback;
    private javax.swing.JRadioButton jRadioButton5_givefeedback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_givefeedback;
    // End of variables declaration//GEN-END:variables
}
