
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ameed
 */
public class NotifyEmployees extends javax.swing.JFrame {

    /**
     * Creates new form NotifyEmployees
     */
    public NotifyEmployees() {
        initComponents();
        this.setDefaultCloseOperation(NotifyEmployees.HIDE_ON_CLOSE);
        model = new DefaultListModel();
        
        users = Search.searchEmployees("");
        
        model.removeAllElements();

        if(!users.isEmpty()){
            for(int i=0 ; i<users.size() ; i++){
                model.addElement(users.get(i).getUsername());
            }
            this.jList_EmployeesAll.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_EmployeesAll = new javax.swing.JList<>();
        jCheckBox_selectAll = new javax.swing.JCheckBox();
        jTextField_message = new javax.swing.JTextField();
        jButton_submitNotification = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 126, 34));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Notify Employees");

        jList_EmployeesAll.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_EmployeesAll.setSelectionBackground(new java.awt.Color(230, 126, 34));
        jList_EmployeesAll.setVisibleRowCount(5);
        jScrollPane1.setViewportView(jList_EmployeesAll);

        jCheckBox_selectAll.setFont(new java.awt.Font("Urdu Typesetting", 1, 12)); // NOI18N
        jCheckBox_selectAll.setText("Select All");
        jCheckBox_selectAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_selectAllItemStateChanged(evt);
            }
        });
        jCheckBox_selectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_selectAllActionPerformed(evt);
            }
        });

        jButton_submitNotification.setText("Send Notification");
        jButton_submitNotification.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 126, 34)));
        jButton_submitNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitNotificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_message))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jButton_submitNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jCheckBox_selectAll)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox_selectAll)
                        .addGap(90, 90, 90)))
                .addComponent(jTextField_message, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_submitNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_selectAllActionPerformed
        
    }//GEN-LAST:event_jCheckBox_selectAllActionPerformed

    private void jCheckBox_selectAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_selectAllItemStateChanged
        int listItems = this.jList_EmployeesAll.getModel().getSize();
        
        if(this.jCheckBox_selectAll.isSelected()){
            this.jList_EmployeesAll.setSelectionInterval(0, listItems - 1);
        } else {
            this.jList_EmployeesAll.removeSelectionInterval(0, listItems - 1);
        }
    }//GEN-LAST:event_jCheckBox_selectAllItemStateChanged

    private void jButton_submitNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitNotificationActionPerformed
        int []selectedItems = this.jList_EmployeesAll.getSelectedIndices();
        String enteredMessage = this.jTextField_message.getText();
        if(selectedItems.length == 0){
            JOptionPane.showMessageDialog(rootPane, "Please choose employees.");
            return;
        }
        if(enteredMessage.length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Please enter message to send");
            return;
        }
        
        for(int i=0 ; i<selectedItems.length;i++){
            Notifications.addNotification(Login.currentUser, 
                                          users.get(i),
                                          enteredMessage);
        }
        
        JOptionPane.showMessageDialog(rootPane, "Done");
        dispose();
    }//GEN-LAST:event_jButton_submitNotificationActionPerformed

    public void displayEmployees(String name){
        users = Search.searchEmployees(name);
        this.jList_EmployeesAll = new javax.swing.JList(model);
        model.removeAllElements();
                        System.out.println("TEST123");

        if(!users.isEmpty()){
            for(int i=0 ; i<users.size() ; i++){
                model.addElement(users.get(i).getUsername());
                System.out.println(model.size());
            }
            this.jList_EmployeesAll.setModel(model);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotifyEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotifyEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotifyEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotifyEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotifyEmployees().setVisible(true);
            }
        });
    }

    // Custom declarations
    private ArrayList<User> users;
    private DefaultListModel model;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_submitNotification;
    private javax.swing.JCheckBox jCheckBox_selectAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList_EmployeesAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_message;
    // End of variables declaration//GEN-END:variables
}
