
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ameed
 */
public class RequestsFrame extends javax.swing.JFrame {

    /**
     * Creates new form RequestsFrame
     */
    
    public RequestsFrame(){
        initComponents();
    }
    
    public RequestsFrame(User reciever, String messageToRepresent) {
        initComponents();
        this.jPanel2_tablePanel.setVisible(true);
        this.jPanel3_specificRequest.setVisible(false);
        this.jLabel1_back.setVisible(false);
        this.setDefaultCloseOperation(RequestsFrame.HIDE_ON_CLOSE);
        this.setResizable(true);
        
        String header = this.jLabel1_name.getText();
        this.jLabel1_name.setText(header.replace("Name", reciever.getUsername()));
        userRequests = Requests.getRequests(reciever);
        this.setDefaultCloseOperation(NotificationsFrame.HIDE_ON_CLOSE);
        DefaultTableModel model = (DefaultTableModel)this.jTable1_allRequests.getModel();
        int rowCount = model.getRowCount();
        for(int i= rowCount - 1 ; i >= 0 ; i--){
            model.removeRow(i);
        }
        if(!userRequests.isEmpty()){
            this.jPanel2_tablePanel.setVisible(true);
            this.jPanel3_specificRequest.setVisible(false);
            for(int i=0 ; i<userRequests.size() ; i++){
                String usersConvertor[] = {userRequests.get(i).getSenderName(), messageToRepresent};
                model.addRow(usersConvertor);
            }
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_name = new javax.swing.JLabel();
        jLabel1_back = new javax.swing.JLabel();
        jPanel2_tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_allRequests = new javax.swing.JTable();
        jPanel3_specificRequest = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1_acceptRequest = new javax.swing.JRadioButton();
        jRadioButton2_rejectRequest = new javax.swing.JRadioButton();
        jButton1_respondRequest = new javax.swing.JButton();
        jLabel1_delete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_name.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1_name.setText("Name's Requests");

        jLabel1_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jLabel1_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_backMouseClicked(evt);
            }
        });

        jTable1_allRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_allRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_allRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_allRequests);
        if (jTable1_allRequests.getColumnModel().getColumnCount() > 0) {
            jTable1_allRequests.getColumnModel().getColumn(0).setResizable(false);
            jTable1_allRequests.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2_tablePanelLayout = new javax.swing.GroupLayout(jPanel2_tablePanel);
        jPanel2_tablePanel.setLayout(jPanel2_tablePanelLayout);
        jPanel2_tablePanelLayout.setHorizontalGroup(
            jPanel2_tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        jPanel2_tablePanelLayout.setVerticalGroup(
            jPanel2_tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1_acceptRequest);
        jRadioButton1_acceptRequest.setSelected(true);
        jRadioButton1_acceptRequest.setText("Yes");

        buttonGroup1.add(jRadioButton2_rejectRequest);
        jRadioButton2_rejectRequest.setText("No");

        jButton1_respondRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1_respondRequest.setText("Submit");
        jButton1_respondRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_respondRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3_specificRequestLayout = new javax.swing.GroupLayout(jPanel3_specificRequest);
        jPanel3_specificRequest.setLayout(jPanel3_specificRequestLayout);
        jPanel3_specificRequestLayout.setHorizontalGroup(
            jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(297, Short.MAX_VALUE)
                    .addComponent(jRadioButton1_acceptRequest)
                    .addContainerGap(228, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(351, Short.MAX_VALUE)
                    .addComponent(jRadioButton2_rejectRequest)
                    .addContainerGap(178, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(jButton1_respondRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(233, Short.MAX_VALUE)))
        );
        jPanel3_specificRequestLayout.setVerticalGroup(
            jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(411, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(jRadioButton1_acceptRequest)
                    .addContainerGap(415, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(jRadioButton2_rejectRequest)
                    .addContainerGap(415, Short.MAX_VALUE)))
            .addGroup(jPanel3_specificRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3_specificRequestLayout.createSequentialGroup()
                    .addContainerGap(115, Short.MAX_VALUE)
                    .addComponent(jButton1_respondRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );

        jLabel1_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_name)
                .addGap(201, 201, 201)
                .addComponent(jLabel1_back)
                .addContainerGap())
            .addComponent(jPanel2_tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3_specificRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1_name))
                    .addComponent(jLabel1_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPanel2_tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(jPanel3_specificRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 517, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_backMouseClicked
        this.jPanel2_tablePanel.setVisible(true);
        this.jPanel3_specificRequest.setVisible(false);
        this.jLabel1_back.setVisible(false);
    }//GEN-LAST:event_jLabel1_backMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1_respondRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_respondRequestActionPerformed
        User currentUser = Search.searchForUser(pressedRequest.getRecieverID(), "");
        if(currentUser.getManagerID() == 0){
            this.jRadioButton1_acceptRequest.setActionCommand("accepted");
            this.jRadioButton2_rejectRequest.setActionCommand("rejected");
            String sub=buttonGroup1.getSelection().getActionCommand();
            Requests.respondRequest(pressedRequest, sub);
            JOptionPane.showMessageDialog(rootPane, sub + " the request.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "You already have a manager, remove it first so you can accept this manager");
        }
        dispose();
    }//GEN-LAST:event_jButton1_respondRequestActionPerformed

    private void jTable1_allRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_allRequestsMouseClicked
        this.pressedRequest = this.userRequests.get(this.jTable1_allRequests.getSelectedRow());
        String requestMsg = String.format("Do you accept %s to be your manager?", pressedRequest.getSenderName());
        this.jTextField1.setText(requestMsg);
        this.jPanel2_tablePanel.setVisible(false);
        this.jPanel3_specificRequest.setVisible(true);
        this.jLabel1_back.setVisible(true);
    }//GEN-LAST:event_jTable1_allRequestsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestsFrame().setVisible(true);
            }
        });
    }

    // Custom Declerations
    
    ArrayList<Requests> userRequests = new ArrayList<>();
    Requests pressedRequest;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_respondRequest;
    private javax.swing.JLabel jLabel1_back;
    private javax.swing.JLabel jLabel1_delete;
    private javax.swing.JLabel jLabel1_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_tablePanel;
    private javax.swing.JPanel jPanel3_specificRequest;
    private javax.swing.JRadioButton jRadioButton1_acceptRequest;
    private javax.swing.JRadioButton jRadioButton2_rejectRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_allRequests;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
