/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.net.URLEncoder;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IrshaiD
 */
public class WeatherFrame extends javax.swing.JFrame {

    /**
     * Creates new form Weather
     */
    
    
    public WeatherFrame(){
        initComponents();
        setLocationRelativeTo(this);
        Location="London";
        weatherForWeek = WeatherForecast.getList(Location);
        weatherForToday = WeatherForecast.getDay(Location);
        if(weatherForToday == null){
            JOptionPane.showMessageDialog(rootPane, "Invalid Location Entereed");
            dispose();
            return;
        }
        System.out.println(weatherForToday.toString());
        setTodayValues();
    }
    
    public WeatherFrame(String location){
        initComponents();
        setLocationRelativeTo(this);
        this.Location = location;
        weatherForWeek = WeatherForecast.getList(Location);
        weatherForToday = WeatherForecast.getDay(Location);
        if(weatherForToday == null){
            JOptionPane.showMessageDialog(rootPane, "Invalid Location Entereed");
            dispose();
            return;
        }
        System.out.println(weatherForToday.toString());
        setTodayValues();
    }

    void setTodayValues(){
        this.jLabel_currentTempValue.setText(Integer.toString(WeatherForecast.FirToCil(weatherForToday.getTemp()))+"°C");
        this.jLabel_feelLikeValue.setText(Integer.toString(WeatherForecast.FirToCil(weatherForToday.getFeelsLike()))+"°C");
        this.jLabel_Description.setText(weatherForToday.getDescription());
        this.jLabel2_location.setText(Location);
        this.jLabel_humidityValue.setText(""+weatherForToday.getHumidity());
        this.jLabel_pressureValue.setText(""+weatherForToday.getPressure()+"%");
        this.jLabel_windSpeedValue.setText(""+weatherForToday.getWindSpeed()+"m/s");     
        this.jLabel_minTempValue.setText(Integer.toString(WeatherForecast.FirToCil(weatherForToday.getMinTemp()))+"°C");
        this.jLabel_maxTempValue.setText(Integer.toString(WeatherForecast.FirToCil(weatherForToday.getMaxTemp()))+"°C");

        if(weatherForToday.getDescription().contains("clear"))
           this.jLabel_DesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Sun_64px_3.png"))); // NOI18N
        else if(weatherForToday.getDescription().contains("cloud"))
           this.jLabel_DesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Cloud_64px.png"))); // NOI18N
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_humidityIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_windSpeedIcon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_pressureIcon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_humidityValue = new javax.swing.JLabel();
        jLabel_windSpeedValue = new javax.swing.JLabel();
        jLabel_pressureValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2_location = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_minTempValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_maxTempValue = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_DesIcon = new javax.swing.JLabel();
        jLabel_Description = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel_feelLikeValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_currentTempValue = new javax.swing.JLabel();
        jLabel_DayMonth = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_day1 = new javax.swing.JLabel();
        jLabel_day1Value = new javax.swing.JLabel();
        jLabel_day2Value = new javax.swing.JLabel();
        jLabel_day2 = new javax.swing.JLabel();
        jLabel_day3 = new javax.swing.JLabel();
        jLabel_day3Value = new javax.swing.JLabel();
        jLabel_day4 = new javax.swing.JLabel();
        jLabel_day4Value = new javax.swing.JLabel();
        jLabel_day5 = new javax.swing.JLabel();
        jLabel_day5Value = new javax.swing.JLabel();
        jLabel_day6 = new javax.swing.JLabel();
        jLabel_day6Value = new javax.swing.JLabel();
        jLabel_day7 = new javax.swing.JLabel();
        jLabel_day7Value = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(74, 45, 91));

        jPanel1.setBackground(new java.awt.Color(74, 45, 91));

        jLabel_humidityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Humidity_44px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Humidity:");

        jLabel_windSpeedIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Wind Speed 98-102_44px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wind Speed:");

        jLabel_pressureIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Atmospheric Pressure-44 (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pressure");

        jLabel_humidityValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_humidityValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_humidityValue.setText("NUMBER");

        jLabel_windSpeedValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_windSpeedValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_windSpeedValue.setText("NUMBER");

        jLabel_pressureValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_pressureValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pressureValue.setText("NUMBER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_humidityIcon)
                    .addComponent(jLabel_windSpeedIcon)
                    .addComponent(jLabel_pressureIcon))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_humidityValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_windSpeedValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_pressureValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_humidityIcon)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_humidityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_windSpeedIcon)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_windSpeedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pressureIcon)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_pressureValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Marker_64px.png"))); // NOI18N

        jLabel2_location.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel2_location.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_location.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_location.setText("Location");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(74, 45, 91));

        jLabel_Time.setFont(new java.awt.Font("Urdu Typesetting", 1, 21)); // NOI18N
        jLabel_Time.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Time.setText("Time");

        jLabel3.setFont(new java.awt.Font("Urdu Typesetting", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Min. Temp.");

        jLabel_minTempValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 21)); // NOI18N
        jLabel_minTempValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minTempValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minTempValue.setText("Value");

        jLabel6.setFont(new java.awt.Font("Urdu Typesetting", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Max. Temp.");

        jLabel_maxTempValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 21)); // NOI18N
        jLabel_maxTempValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_maxTempValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_maxTempValue.setText("Value");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Thermometer-64.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Thermometer-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_minTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_maxTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(184, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_minTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_maxTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(141, 141, 141)))
        );

        jLabel_DesIcon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DesIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherIcons/Sun_64px_3.png"))); // NOI18N

        jLabel_Description.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel_Description.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Description.setText("Description");

        jLabel.setFont(new java.awt.Font("Urdu Typesetting", 1, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("FEELS LIKE:");

        jLabel_feelLikeValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel_feelLikeValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_feelLikeValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_feelLikeValue.setText("Value");

        jPanel3.setBackground(new java.awt.Color(67, 41, 82));

        jLabel_currentTempValue.setFont(new java.awt.Font("Urdu Typesetting", 1, 28)); // NOI18N
        jLabel_currentTempValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_currentTempValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_currentTempValue.setText("currentTemp");

        jLabel_DayMonth.setFont(new java.awt.Font("Urdu Typesetting", 1, 12)); // NOI18N
        jLabel_DayMonth.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DayMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DayMonth.setText("Saturday, 7TH");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_day1.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day1.setText("Day1");

        jLabel_day1Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day1Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day1Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day1Value.setText("jLabel13");

        jLabel_day2Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day2Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day2Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day2Value.setText("jLabel13");

        jLabel_day2.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day2.setText("Day2");

        jLabel_day3.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day3.setText("Day3");

        jLabel_day3Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day3Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day3Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day3Value.setText("jLabel13");

        jLabel_day4.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day4.setText("Day4");

        jLabel_day4Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day4Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day4Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day4Value.setText("jLabel13");

        jLabel_day5.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day5.setText("Day5");

        jLabel_day5Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day5Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day5Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day5Value.setText("jLabel13");

        jLabel_day6.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day6.setText("Day6");

        jLabel_day6Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day6Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day6Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day6Value.setText("jLabel13");

        jLabel_day7.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel_day7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day7.setText("Day7");

        jLabel_day7Value.setFont(new java.awt.Font("Urdu Typesetting", 0, 16)); // NOI18N
        jLabel_day7Value.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_day7Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_day7Value.setText("jLabel13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_DayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_currentTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day1Value, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day3Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day4Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day5Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day6Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_day7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_day7Value, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day1Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_currentTempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_DayMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day2Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day3Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day4Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day5Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day6Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_day7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_day7Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel_DesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_feelLikeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Description, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(jLabel2_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(168, 168, 168)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(561, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2_location, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_DesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_feelLikeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherFrame().setVisible(true);
            }
        });
    }

    // Custom declarations

    private ArrayList<WeatherForecast> weatherForWeek;
    private WeatherForecast weatherForToday;
    private String Location;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2_location;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DayMonth;
    private javax.swing.JLabel jLabel_DesIcon;
    private javax.swing.JLabel jLabel_Description;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JLabel jLabel_currentTempValue;
    private javax.swing.JLabel jLabel_day1;
    private javax.swing.JLabel jLabel_day1Value;
    private javax.swing.JLabel jLabel_day2;
    private javax.swing.JLabel jLabel_day2Value;
    private javax.swing.JLabel jLabel_day3;
    private javax.swing.JLabel jLabel_day3Value;
    private javax.swing.JLabel jLabel_day4;
    private javax.swing.JLabel jLabel_day4Value;
    private javax.swing.JLabel jLabel_day5;
    private javax.swing.JLabel jLabel_day5Value;
    private javax.swing.JLabel jLabel_day6;
    private javax.swing.JLabel jLabel_day6Value;
    private javax.swing.JLabel jLabel_day7;
    private javax.swing.JLabel jLabel_day7Value;
    private javax.swing.JLabel jLabel_feelLikeValue;
    private javax.swing.JLabel jLabel_humidityIcon;
    private javax.swing.JLabel jLabel_humidityValue;
    private javax.swing.JLabel jLabel_maxTempValue;
    private javax.swing.JLabel jLabel_minTempValue;
    private javax.swing.JLabel jLabel_pressureIcon;
    private javax.swing.JLabel jLabel_pressureValue;
    private javax.swing.JLabel jLabel_windSpeedIcon;
    private javax.swing.JLabel jLabel_windSpeedValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
